### ISSUE TITLE
some log are incorrect

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [tallbl0nde/NX-Activity-Log#22] opened 2020-02-19 18:12 UTC
I don't know what happened on January 13, 2020, there's something wrong with that day's log. Only that day has this problem, other days log and the all activity's total log are correct.
I use the emummc, firmware 9.1, atmosphere 0.10.2
Can I fix or delete this day's log?
![1](https://user-images.githubusercontent.com/52705310/74861037-a3f8c700-5384-11ea-9ecf-b6148cb07baa.jpg)
![2](https://user-images.githubusercontent.com/52705310/74861040-a529f400-5384-11ea-9d4d-de0b1eea2959.jpg)
![4](https://user-images.githubusercontent.com/52705310/74861046-a8bd7b00-5384-11ea-9d4e-ebb53dd7ab64.jpg)
![3](https://user-images.githubusercontent.com/52705310/74861048-a9561180-5384-11ea-9719-d14f9617e29c.jpg)

**Comment by tallbl0nde** [comment] 2020-02-19 20:16
Hmm... that's interesting. However I'm assuming the session events are correct so it could just be an error in my math somewhere.

Could you download and run the .nro from [here](https://github.com/tallbl0nde/PlayEventParser/releases/tag/v1.0.0)? It will create playlog.txt on the root of your sd. Please upload that and then I should be able to determine what the issue is.

**Comment by Heartbeat-Heartbreak** [comment] 2020-02-20 01:08
I want to do this, but I don't know how to compile it. I'm just a code noob, can you give me a compiled nro?

**Comment by tallbl0nde** [comment] 2020-02-20 01:13
Sorry I forgot to upload the nro, it should be there now!

**Comment by Heartbeat-Heartbreak** [comment] 2020-02-20 01:24
[playlog.txt](https://github.com/tallbl0nde/NX-Activity-Log/files/4228319/playlog.txt)
is it？

**Comment by tallbl0nde** [comment] 2020-02-20 01:31
Ok I think I can see what's happening (it doesn't matter if you don't quite get this as I'm noting it down for later):

Essentially after the game is launched it's saying it's been minimised before it was actually "played".
I guess this would be due to suspending it at the "nintendo switch" loading screen.

I can't really fix it right now but once I have it would be great if you could test it for me :)

**Comment by Heartbeat-Heartbreak** [comment] 2020-02-20 01:42
In fact, I find this problem last month, but because some language barriers so I didn't feedback -_- ||
Your last amazinnnng release reminded me of this problem,I love it. if you need, I will do my best to help your test

**Comment by tallbl0nde** [comment] 2020-02-26 07:36
Hopefully this fixes it - it should at least fix Pokemon, I'm not sure about Xenoblade 2 though. If Xenoblade 2 is still incorrect please upload another screenshot for the Xenoblade play sessions!

Also please check that your other playtime is still the same (it should be).
[NX-Activity-Log.zip](https://github.com/tallbl0nde/NX-Activity-Log/files/4254031/NX-Activity-Log.zip)

**Comment by Heartbeat-Heartbreak** [comment] 2020-02-26 15:17
Sorry for late, It seems you fix the total playtime, 
![2020022622193000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/52705310/75353819-f8e98f80-58e6-11ea-95e2-b982d4932407.jpg)

but some things still incorrect:
![2020022622195000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/52705310/75353987-36e6b380-58e7-11ea-876b-33a377a84675.jpg)
![2020022622195400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/52705310/75354012-3f3eee80-58e7-11ea-8486-2ac7c9db11f4.jpg)
![2020022622200300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/52705310/75354050-4e25a100-58e7-11ea-914f-c907c1621d09.jpg)
![2020022622303600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/52705310/75354473-fb001e00-58e7-11ea-8ffb-90e83f2bc3c2.jpg)

**Comment by tallbl0nde** [comment] 2020-02-26 23:46
I _think_ that should be fixed now too...
[NX-Activity-Log.zip](https://github.com/tallbl0nde/NX-Activity-Log/files/4258759/NX-Activity-Log.zip)

**Comment by Heartbeat-Heartbreak** [comment] 2020-02-27 00:14
Yeah! you did it!  It took me a while to check all the logs and they are all correct! (｡･ω･｡)ﾉ♡cheer for you!

**Comment by Heartbeat-Heartbreak** [comment] 2020-02-27 00:21
I found another problem, but looks like someone has already post it.
This program supports Japanese character, but not traditional Chinese (simplified Chinese may be the same)
![IMG_20200227_080600](https://user-images.githubusercontent.com/52705310/75400196-7f2ec180-5939-11ea-848b-d7fd2b590cb5.jpg)
![IMG_20200227_080505](https://user-images.githubusercontent.com/52705310/75400200-82c24880-5939-11ea-933b-e9a7e55ecbb5.jpg)

**Comment by tallbl0nde** [comment] 2020-02-27 00:41
I think I know how to fix it, it's just a matter of getting around to it! Seeing how I've fixed the playtime I'll close this issue, thank you for testing! :)

**Closed by tallbl0nde** 2020-02-27 00:41 UTC
